# Generated by Django 5.0.2 on 2024-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ano_fundacao', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ano de Fundação')),
                ('divisao', models.CharField(choices=[('A', 'Serie A'), ('B', 'Serie B'), ('C', 'Serie C'), ('D', 'Serie D')], max_length=20, verbose_name='Divisão')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagem', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Jogadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagem', verbose_name='Imagem')),
                ('clube', models.CharField(max_length=50)),
                ('posicao', models.CharField(choices=[('Gol', 'Goleiro'), ('Zag', 'Zagueiro'), ('Lat', 'Lateral'), ('Vol', 'Volante'), ('Mei', 'Meio-Campista'), ('Pont', 'Ponta'), ('ATA', 'Atacante')], max_length=30, verbose_name='Posição  do jogador')),
                ('numero', models.PositiveIntegerField(default=0)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=20)),
            ],
        ),
    ]
