# Generated by Django 5.0.2 on 2024-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='competicoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estadual', models.CharField(max_length=100)),
                ('nacional', models.CharField(max_length=100)),
                ('internacional', models.CharField(max_length=100)),
            ],
        ),
    ]
