# Generated by Django 5.0.2 on 2024-03-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_competicoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicoe',
            name='estadual',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='competicoe',
            name='internacional',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='competicoe',
            name='nacional',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
