# Generated by Django 5.0.2 on 2024-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_alter_competicoe_estadual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Clube')),
                ('ano_conquista', models.PositiveIntegerField(default=0)),
                ('data_exata', models.DateField(blank=True, null=True, verbose_name='Data exata ')),
            ],
        ),
    ]
