# Generated by Django 5.0.2 on 2024-03-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0006_alter_titulo_ano_conquista'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='nome_titulo',
            field=models.CharField(max_length=50, null=True, verbose_name='Titulo'),
        ),
    ]
